# Generated by Django 5.2.8 on 2025-11-11 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tasks',
            new_name='Task',
        ),
    ]
