# Generated by Django 5.2.8 on 2025-11-11 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_app', '0002_rename_tasks_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_id', models.CharField(max_length=20, unique=True)),
                ('action_type', models.CharField(choices=[('Comment', 'Comment'), ('Status Update', 'Status Update'), ('Follow up', 'Follow up'), ('Reminder', 'Reminder')], max_length=100)),
                ('note', models.TextField()),
                ('performed_by', models.CharField(max_length=255)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='activity_app.task')),
            ],
        ),
    ]
