# Generated by Django 5.1.2 on 2025-11-17 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_app', '0005_remainder_delete_reminder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remainder',
            old_name='reminder_date',
            new_name='remainder_date',
        ),
    ]
